#Simple workfow to build CoreELEC for Phicomm N1
name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the n1-19 branch
#  push:
    #branches: [ n1-19 ]
#  pull_request:
    #branches: [ n1-19 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache downloaded packages
        uses: actions/cache@v2
        with:
          path: |
                sources
          key: CoreELEC-Phicomm-N1-sources-Linux-f658d7aaa8d24611e03401b1dd7ba2d170a8c01b3f84a34d29e03cb480f9f0f6
          
      - name: List folder
        working-directory: /home/runner/work/CoreELEC/CoreELEC
        run: |
          pwd
          ls -ltr
      
